version: 2
updates:
  # Enable version updates for library itself
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typedoc-plugin-markdown"
        update-types: ["version-update:semver-major"]
    groups:
      internal-tooling:
        patterns:
          - "@inrupt/internal-*"
          - "@inrupt/base-*"
          - "@inrupt/jest-*"
          - "@inrupt/eslint-*"
      external-types:
        patterns:
          - "@types/*"

  - package-ecosystem: "npm"
    # Upgrade dependencies for the browser-based test app.
    directory: "/e2e/browser/test-app"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
    groups:
      external-types:
        patterns:
          - "@types/*"

  # Enable version updates for the website tooling
  - package-ecosystem: "pip"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/docs"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"

  # Enable version updates for our CI tooling
  - package-ecosystem: "github-actions"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
