name: CI

on: [push]

env:
  CI: true
jobs:
  lint:
    uses: inrupt/javascript-style-configs/.github/workflows/reusable-lint.yml@v1.1.0

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run test:e2e:node
        # To prevent conflicts of multiple jobs trying to modify the same Resource at the same time,
        # and because behaviour on different OS's is already tested by unit tests,
        # end-to-end tests only need to run on one OS:
        if: runner.os == 'Linux' && matrix.node-version == '16.x' && github.actor != 'dependabot[bot]'
        env:
          E2E_TEST_IDP: ${{ secrets.E2E_TEST_IDP }}
          E2E_TEST_VC_PROVIDER: https://vc.dev-next.inrupt.com
          E2E_TEST_VC_SUBJECT: https://id.dev-next.inrupt.com/sdkdevnexte2e
          E2E_TEST_OWNER_CLIENT_ID: ${{ secrets.E2E_TEST_REQUESTOR_CLIENT_ID }}
          E2E_TEST_OWNER_CLIENT_SECRET: ${{ secrets.E2E_TEST_REQUESTOR_CLIENT_SECRET }}
