name: CI

on: [push]

env:
  CI: true
jobs:
  lint:
    uses: inrupt/typescript-sdk-tools/.github/workflows/reusable-lint.yml@v1.1.0

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm run build
      - run: npm run test

      # Sonar analysis needs the full history for features like automatic assignment of bugs. If the following step
      # is not included the project will show a warning about incomplete information.
      - run: git fetch --unshallow
        if: ${{ matrix.node-version == '16.x' && runner.os == 'Linux' && github.actor != 'dependabot[bot]' }}
      # Run Sonar Scan
      - uses: SonarSource/sonarcloud-github-action@v1.7
        if: ${{ matrix.node-version == '16.x' && runner.os == 'Linux' && github.actor != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
